resources:
- oauth.yaml
- project-leaders.yaml
- self-provisioners.yaml
secretGenerator:
- name: htpasswd
  namespace: deploy-jenkins
  files:
  - htpasswd=htpasswd-secret-data
generatorOptions:
  disableNameSuffixHash: true
